{
  parserClass="com.wilfcastle.gdscript.parser.GDScriptParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="GDScript"
  psiImplClassSuffix="Impl"
  psiPackage="com.wilfcastle.gdscript.psi"
  psiImplPackage="com.wilfcastle.gdscript.impl"

  elementTypeHolderClass="com.wilfcastle.gdscript.psi.GDScriptTypes"
  elementTypeClass="com.wilfcastle.gdscript.psi.GDScriptElementType"
  tokenTypeClass="com.wilfcastle.gdscript.psi.GDScriptTokenType"
}

gdScriptFile ::= item_*

private item_ ::= (assignment|COMMENT)

private literal_ ::= (NUMBER|STRING|array|dict)

private declaration_keyword_ ::= (VAR|CONST)

array ::= (OPEN_SQ_BRACKET (literal_ (COMMA literal_)*)? CLOSED_SQ_BRACKET)

private dict_pair_ ::= (literal_ COLON literal_)

dict ::= (OPEN_CURLY_BRACKET  ((dict_pair_) (COMMA dict_pair_)*)? CLOSED_CURLY_BRACKET)

assignment ::= (declaration_keyword_ IDENTIFIER EQUALS literal_)
